create table carteira (id integer generated by default as identity, id_corretora integer, primary key (id))
create table corretora (id integer generated by default as identity, nome varchar(255), primary key (id))
alter table carteira add constraint FKfcn4qwuaapc08qg1eb4ujn8j2 foreign key (id_corretora) references corretora
create table carteira (id integer generated by default as identity, id_corretora integer, primary key (id))
create table corretora (id integer generated by default as identity, nome varchar(255), primary key (id))
alter table carteira add constraint FKfcn4qwuaapc08qg1eb4ujn8j2 foreign key (id_corretora) references corretora
create table carteira (id integer generated by default as identity, id_corretora integer, primary key (id))
create table corretora (id integer generated by default as identity, nome varchar(255), primary key (id))
alter table carteira add constraint FKfcn4qwuaapc08qg1eb4ujn8j2 foreign key (id_corretora) references corretora
